version: '3.8'

services:
  frontend:
    build: './frontend'
    ports:
      - "127.0.0.1:8082:3000"

  auto_kmdb:
    build: './auto_kmdb'
    volumes:
      - type: bind
        source: ./data
        target: /data
    ports:
      - "8080:8000"
    env_file:
      - auto_kmdb.env

volumes:
  shared-models:
  data:

