version: '3.8'

services:
  ssh_tunnel:
    build: './ssh_tunnel'
    ports:
      - "127.0.0.1:9999:9999"
      - "127.0.0.1:1080:1080"
    volumes:
      - type: bind
        source: ./secrets
        target: /secrets
    hostname: ssh_tunnel
    restart: unless-stopped

  frontend:
    build: './frontend'
    ports:
      - "127.0.0.1:8082:3000"
    restart: unless-stopped

  auto_kmdb:
    build: './auto_kmdb'
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/app/webapp/data
    ports:
      - "8080:8000"
    env_file:
      - auto_kmdb.env
    restart: unless-stopped

volumes:
  shared-models:
  data:

